version: "3.8"

services:
  gateway-service:
    build: ./gateway_service
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
    depends_on:
      - consul
    networks:
      - gateway-network

  auth-service:
    build: ./auth_service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: chimera_iam
      DB_USER: postgres
      DB_PASSWORD: naveen2007
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
