version: "3.8"

services:
  gateway-service:
    build:
      context: ./gateway_service
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
    depends_on:
      - consul
    networks:
      - gateway-network

  auth-service:
    build:
      context: ./auth_service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: chimera_iam
      DB_USER: postgres
      DB_PASSWORD: naveen2007
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  user-service:
    build:
      context: ./user_service
    ports:
      - "5035:5035"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: http://+:5035
      ConnectionStrings__DefaultConnection: Host=host.docker.internal;Database=chimera_iam;Username=postgres;Password=naveen2007
      Consul__Host: consul
      Consul__Port: 8500
      Consul__Scheme: http
      Consul__Discovery__Enabled: "true"
      Consul__Discovery__Register: "true"
      Consul__Discovery__Deregister: "true"
      Consul__Discovery__HostName: user-service
      Consul__Discovery__Port: 5035
      Consul__Discovery__ServiceName: user-service
      Consul__Discovery__Heartbeat__Enabled: "true"
      Consul__Discovery__Heartbeat__TtlValue: 15
      Consul__Discovery__Heartbeat__TtlUnit: s
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  gene-bank-service:
    build:
      context: ./gene_bank_service
    ports:
      - "5050:5050"
    environment:
      CONSUL_HOST: "host.docker.internal"
      CONSUL_PORT: "8500"
      SERVICE_HOST: "host.docker.internal"
      SERVICE_NAME: "gene-bank-service"
      SERVICE_PORT: "5050"
      STATUS: "passing"
      INTERVAL: "15s"
      TIMEOUT: "10s"
      DEREGISTER_CRITICAL_SERVICE_AFTER: "5m"
      APP_PORT: "5050"
      RABBITMQ_URL: "amqp://admin:naveen@2007@host.docker.internal:5672"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  flora-upstream-service:
    build:
      context: ./flora_upstream_service
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: "postgresql://postgres:naveen2007@host.docker.internal:5432/chimera_flora?schema=public"
      DATABASE_URL_MONGO: "mongodb://host.docker.internal:27017/chimera_flora"
      PORT: 3030
      RABBIT_MQ_URL: "amqp://admin:naveen@2007@host.docker.internal:5672"
      RABBIT_QUEUE_FLORA: "flora_upstream_queue"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  flora-downstream-service:
    build:
      context: ./flora_downstream_service
    ports:
      - "8100:8100"
    environment:
      PYTHONUNBUFFERED: 1
      PIP_NO_CACHE_DIR: "off"
      ENVIRONMENT: "production"
      CONSUL_HOST: "host.docker.internal"
      CONSUL_PORT: 8500
      APP_PORT: 8100
      DATABASE_URL_MONGO: "mongodb://host.docker.internal:27017"
      DATABASE_URL_POSTGRES: "postgresql+asyncpg://postgres:naveen2007@host.docker.internal:5432/chimera_flora"
      RABBITMQ_URL: "amqp://admin:naveen@2007@host.docker.internal:5672"
      QUEUE_NAME: "flora_downstream_queue"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - gateway-network

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
